spring:
  application:
    name: g_74_shop
    #   вказуємо реквізити підключення до бази
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/g_74_shop
    username: postgres
    password: qwerty007
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  file:
    name: logs/log.log
  level:
    root: info
# или    root: debug

